# Generated by Django 2.2.5 on 2021-06-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210627_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facilies',
            new_name='facilities',
        ),
    ]
